# Declarative list of activity definitions synchronized by the gem.
# You can use ERB here if you want 

activity_definitions:
  # --- EXAMPLES -------------------------------------------------------------
  # - model_type: "Shipment"
  #   model_event_name: "created"
  #   log_type: "ShipmentCreationLog"
  #
  # - model_type: "Shipment"
  #   model_event_name: "approved"
  #   log_type: "ShipmentApprovalLog"
  #
  # - model_type: "Invoice"
  #   model_event_name: "paid"
  #   log_type: "InvoicePaymentLog"
  #
  # --- ADD YOUR DEFINITIONS BELOW ------------------------------------------
